// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB0tvFO3cfeQQycF1rOW8dS_FBtIwKhI4',
    appId: '1:885545835957:web:908c9bc8320eb5bafa8dfc',
    messagingSenderId: '885545835957',
    projectId: 'vakapp-4fa70',
    authDomain: 'vakapp-4fa70.firebaseapp.com',
    storageBucket: 'vakapp-4fa70.appspot.com',
    measurementId: 'G-V1M90CV3TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzbFUil2YDYtVZFuPAyAVzkBn51nNxC5M',
    appId: '1:885545835957:android:a98cf31b341e667dfa8dfc',
    messagingSenderId: '885545835957',
    projectId: 'vakapp-4fa70',
    storageBucket: 'vakapp-4fa70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7rRLrHwUGXY1N0nQnzE5Jj_z-UYnS_Uo',
    appId: '1:885545835957:ios:a5064f9c450815effa8dfc',
    messagingSenderId: '885545835957',
    projectId: 'vakapp-4fa70',
    storageBucket: 'vakapp-4fa70.appspot.com',
    iosBundleId: 'com.example.vakapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7rRLrHwUGXY1N0nQnzE5Jj_z-UYnS_Uo',
    appId: '1:885545835957:ios:4dd0c3e9dad359a4fa8dfc',
    messagingSenderId: '885545835957',
    projectId: 'vakapp-4fa70',
    storageBucket: 'vakapp-4fa70.appspot.com',
    iosBundleId: 'com.example.vakapp.RunnerTests',
  );
}
